DROP TABLE user IF EXISTS;
CREATE TABLE user (
  user_id      BIGINT GENERATED BY DEFAULT AS identity,
  date_created BINARY(255),
  email        VARCHAR(255),
  first_name   VARCHAR(255),
  last_name    VARCHAR(255),
  password     VARCHAR(255),
  uuid         VARCHAR(255),
  PRIMARY KEY (user_id)
);